-- 코드를 입력하세요

-- FETCH 가져오기
-- FETCH FIRST N ROW ONLY : 상위 N개

-- OFFSET 건너뛰기
-- OFFSET N ROWS FETCH NEXT M ROWS ONLY : N개 건너뛰고 M개만

SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME
FETCH FIRST 1 ROW ONLY;