-- 코드를 입력하세요

-- NVL(TLNO, 'NONE') AS TLNO

-- CASE 
--     WHEN TLNO IS NULL THEN 'NONE'
--     ELSE TLNO
-- END AS TLNO

SELECT PT_NAME, PT_NO, GEND_CD, AGE, NVL(TLNO, 'NONE') AS TLNO FROM PATIENT
WHERE AGE <= 12 AND GEND_CD='W'
ORDER BY AGE DESC, PT_NAME ASC;