-- 코드를 입력하세요

-- YEAR
-- WHERE EXTRACT(YEAR FROM PUBLISHED_DATE)=2021
-- WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY')='2021'
-- WHERE PUBLISHED_DATE >= DATE '2021-01-01' AND PUBLISHED_DATE < DATE '2022-01-01'

SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE FROM BOOK
WHERE EXTRACT(YEAR FROM PUBLISHED_DATE)=2021 AND CATEGORY='인문'
ORDER BY PUBLISHED_DATE ASC;